# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
