# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pub_date',
        ),
    ]
