# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_profile_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_info',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
